# Generated by Django 4.2.3 on 2023-08-05 13:20

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_category",
                    models.CharField(
                        choices=[
                            ("exercise", "EXERCISE"),
                            ("meditation", "MEDITATION"),
                            ("reading", "READING"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "reward_poin_type",
                    models.CharField(
                        choices=[
                            ("poin_brain", "POIN BRAIN"),
                            ("poin_heart", "POIN HEARTH"),
                            ("poin_muscle", "POIN MUSCLE"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reward_poin_value", models.IntegerField(blank=True, null=True)),
                (
                    "target_type",
                    models.CharField(
                        choices=[("time", "TIME"), ("amount", "AMOUNT")], max_length=32
                    ),
                ),
                ("target_value", models.IntegerField(blank=True, null=True)),
                (
                    "target_unit",
                    models.CharField(
                        choices=[("second", "SECOND"), ("star", "STAR")], max_length=32
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "tasks",
            },
        ),
    ]
