# Generated by Django 4.2.3 on 2023-08-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="target_unit",
            field=models.CharField(
                choices=[("second", "SECOND"), ("star", "STAR"), ("did", "DID")],
                max_length=32,
            ),
        ),
    ]
