# Generated by Django 4.2.3 on 2023-08-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_alter_task_target_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="reward_poin_type",
            field=models.CharField(
                choices=[
                    ("poin_brain", "POIN BRAIN"),
                    ("poin_heart", "POIN HEART"),
                    ("poin_muscle", "POIN MUSCLE"),
                ],
                max_length=32,
            ),
        ),
    ]
