# Generated by Django 4.2.3 on 2023-08-05 09:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0003_tasklog_recommendationlog_eventreward"),
        ("activities", "0002_urgecategory_alter_activity_table_recommendation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fqid", models.CharField(max_length=128)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("choose_click", "CHOOSE_CLICK"),
                            ("start_click", "START_CLICK"),
                            ("ok_completed_click", "OK_COMPLETED_CLICK"),
                            ("play_click", "PLAY_CLICK"),
                            ("back_click", "BACK_CLICK"),
                            ("ok_close_click", "OK_CLOSE_CLICK"),
                            ("grant_permission_click", "GRANT_PERMISSION_CLICK"),
                            ("choose_answer_quiz_click", "CHOOSE_ANSWER_QUIZ_CLICK"),
                        ],
                        max_length=100,
                    ),
                ),
                ("issue_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "activity_id",
                    models.ForeignKey(
                        db_column="activity_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="activities.activity",
                    ),
                ),
                (
                    "activity_log_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="activity_log_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.activitylog",
                    ),
                ),
            ],
            options={
                "db_table": "logger_activity_events",
            },
        ),
    ]
