# Generated by Django 4.2.3 on 2023-08-05 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0001_initial"),
        ("users", "0002_alter_object_background_id_alter_object_character_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="object",
            name="background_id",
            field=models.ForeignKey(
                blank=True,
                db_column="background_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="object_background",
                to="items.item",
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="character_id",
            field=models.ForeignKey(
                blank=True,
                db_column="character_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="object_character",
                to="items.item",
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="clothes_id",
            field=models.ForeignKey(
                blank=True,
                db_column="clothes_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="object_clothes",
                to="items.item",
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="hat_id",
            field=models.ForeignKey(
                blank=True,
                db_column="hat_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="object_hat",
                to="items.item",
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="shoes_id",
            field=models.ForeignKey(
                blank=True,
                db_column="shoes_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="object_shoes",
                to="items.item",
            ),
        ),
    ]
