# Generated by Django 4.2.3 on 2023-08-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0001_initial"),
        ("users", "0003_alter_object_background_id_alter_object_character_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bag_items",
            field=models.ManyToManyField(through="users.Bag", to="items.item"),
        ),
    ]
