# Generated by Django 4.2.3 on 2023-08-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_bag_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendationlog",
            name="urge_level",
            field=models.CharField(
                choices=[
                    ("very_low", "VERY_LOW"),
                    ("low", "LOW"),
                    ("medium", "MEDIUM"),
                    ("high", "HIGH"),
                    ("very_heigh", "VERY_HEIGH"),
                ],
                default="medium",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="recommendationlog",
            name="issue_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="recommendationlog",
            unique_together={("user_id", "issue_at")},
        ),
        migrations.RemoveField(
            model_name="recommendationlog",
            name="recommendation_id",
        ),
    ]
