# Generated by Django 4.2.3 on 2023-08-05 13:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "events",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("character", "CHARACTER"),
                            ("background", "BACKGROUND"),
                            ("hat", "HAT"),
                            ("clothes", "CLOTHES"),
                            ("shoes", "SHOES"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "COMMON"),
                            ("rare", "RARE"),
                            ("epic", "EPIC"),
                            ("mythic", "MYTHIC"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "price_type",
                    models.CharField(
                        choices=[
                            ("gold", "GOLD"),
                            ("poin_brain", "POIN BRAIN"),
                            ("poin_heart", "POIN HEARTH"),
                            ("poin_muscle", "POIN MUSCLE"),
                        ],
                        max_length=32,
                    ),
                ),
                ("price_value", models.IntegerField(blank=True, null=True)),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("none", "NONE"),
                            ("shop", "SHOP"),
                            ("event", "EVENT"),
                        ],
                        default="none",
                        max_length=32,
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("none", "NONE"),
                            ("percent", "PERCENT"),
                            ("amount", "AMOUNT"),
                        ],
                        default="none",
                        max_length=32,
                    ),
                ),
                ("discount_value", models.IntegerField(blank=True, null=True)),
                ("thumbnail_path", models.TextField(blank=True, null=True)),
                ("sprite_path", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "items",
            },
        ),
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event_id",
                    models.ForeignKey(
                        db_column="event_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="items.event",
                    ),
                ),
                (
                    "item_id",
                    models.ForeignKey(
                        db_column="item_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="items.item",
                    ),
                ),
            ],
            options={
                "db_table": "rewards",
            },
        ),
    ]
