# Generated by Django 4.2.3 on 2023-08-09 09:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reward",
            unique_together={("event_id", "item_id")},
        ),
    ]
