# Generated by Django 4.2.3 on 2023-08-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recommendation",
            name="urge_category",
        ),
        migrations.AddField(
            model_name="recommendation",
            name="urge_level",
            field=models.CharField(
                choices=[
                    ("very_low", "VERY_LOW"),
                    ("low", "LOW"),
                    ("medium", "MEDIUM"),
                    ("high", "HIGH"),
                    ("very_heigh", "VERY_HEIGH"),
                ],
                default="medium",
                max_length=32,
            ),
        ),
        migrations.DeleteModel(
            name="UrgeCategory",
        ),
    ]
