# Generated by Django 4.2.3 on 2023-08-05 09:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UrgeCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("prediction_min", models.FloatField(blank=True, null=True)),
                ("prediction_max", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "urges_categories",
            },
        ),
        migrations.AlterModelTable(
            name="activity",
            table="activities",
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "activity_id",
                    models.ForeignKey(
                        db_column="activity_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="activities.activity",
                    ),
                ),
                (
                    "urge_category",
                    models.ForeignKey(
                        db_column="urge_category_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="activities.urgecategory",
                    ),
                ),
            ],
            options={
                "db_table": "activities_recommendations",
            },
        ),
    ]
